// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(ZooContext))]
    [Migration("20201030124153_DataSeed")]
    partial class DataSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataLayer.Entitys.Dyr", b =>
                {
                    b.Property<int>("DyrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Antal")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DyrId");

                    b.HasIndex("UserId");

                    b.ToTable("Dyrs");

                    b.HasData(
                        new
                        {
                            DyrId = 1,
                            Antal = 0,
                            Navn = "Elefant"
                        },
                        new
                        {
                            DyrId = 2,
                            Antal = 0,
                            Navn = "Abe"
                        },
                        new
                        {
                            DyrId = 3,
                            Antal = 0,
                            Navn = "Tiger"
                        },
                        new
                        {
                            DyrId = 4,
                            Antal = 0,
                            Navn = "Løve"
                        },
                        new
                        {
                            DyrId = 5,
                            Antal = 0,
                            Navn = "Flodhest"
                        },
                        new
                        {
                            DyrId = 6,
                            Antal = 0,
                            Navn = "Dovendyr"
                        });
                });

            modelBuilder.Entity("DataLayer.Entitys.Kunder", b =>
                {
                    b.Property<int>("KundeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Antal")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("KundeId");

                    b.HasIndex("UserId");

                    b.ToTable("Kunders");

                    b.HasData(
                        new
                        {
                            KundeId = 1,
                            Antal = 0,
                            Navn = "Famile"
                        },
                        new
                        {
                            KundeId = 2,
                            Antal = 0,
                            Navn = "Par"
                        },
                        new
                        {
                            KundeId = 3,
                            Antal = 0,
                            Navn = "Unge"
                        });
                });

            modelBuilder.Entity("DataLayer.Entitys.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DyrID")
                        .HasColumnType("int");

                    b.Property<int?>("KundeID")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Penge")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DataLayer.Entitys.Dyr", b =>
                {
                    b.HasOne("DataLayer.Entitys.User", "User")
                        .WithMany("Dyrs")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("DataLayer.Entitys.Kunder", b =>
                {
                    b.HasOne("DataLayer.Entitys.User", "User")
                        .WithMany("Kunders")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
